services:
  mongo-service:
    image: mongo
    ports:
     - "27017:27017"
  flask-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     - "5001:5000"
    depends_on:
      - mongo-service